[build]
  builder = "nixpacks"

[deploy]
  healthcheckPath = "/health"
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10

[environments.production]
  [environments.production.variables]
    RAILS_ENV = "production"
